server:
  port: 7001
spring:
  application:
    name: order-7001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka

# 配置ribbon调用支付服务采用的负载均衡策略
payment:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#超时配置，只适用于feign这种调用，不适用restTemplate
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000




